- name: MariaDB installation
  hosts: all
  become: yes
  tasks:
    # - name: Wait 30 seconds for port 22 to become open and contain "OpenSSH"
    #   ansible.builtin.wait_for:
    #     port: 22
    #     host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
    #     search_regex: OpenSSH
    #     delay: 10
    - name: Wait 300 seconds, but only start checking after 60 seconds
      ansible.builtin.wait_for_connection:
        delay: 10
        sleep: 5
        timeout: 120
      connection: local
    - name: Install firewalld
      ansible.builtin.dnf:
        name:
          - firewalld
        state: latest 
    - name: Install httpd service
      ansible.builtin.dnf:
        name:
          - httpd
        state: latest
    - name: enable and start httpd service
      systemd:
        name: httpd
        state: started
        enabled: yes
    - name: enable and start firewalld service
      systemd:
        name: firewalld
        state: started
        enabled: yes
    - name: permit traffic in default zone on port 22/tcp
      ansible.posix.firewalld:
        port: 22/tcp
        permanent: yes
        state: enabled
        immediate: yes
    - name: permit traffic in default zone on port 3306/tcp
      ansible.posix.firewalld:
        port: 3306/tcp
        permanent: yes
        state: enabled
        immediate: yes
    - name: Install MariaDB server
      ansible.builtin.dnf:
        name:
          - mariadb-server
        state: latest
    - name: start MariaDB service
      systemd:
        name: mariadb
        state: started
    - name: verify installation
      ansible.builtin.command: mysql --version
      register: mysql_version
    - debug: var=mysql_version.stdout_lines
